FROM nginx:alpine

# nginx-Config aus dem Repo ins Image
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# statische Dateien (CSS/JS/Assets) aus public ins Image
COPY projekt/public /var/www/html/public
